### ISSUE TITLE
Fundamentals Jan 2023 

### ISSUE THREAD

**Issue by dvirlar2** [NCEAS/nceas-training#144]
**Following chapters have been proofread:**
<details>
   <summary> <i>Click to Expand</i> </summary>

- [ ] Chapter 1
- [ ] Chapter 2
- [ ] Chapter 3
- [x] Chapter 4
- [ ] Chapter 5
- [ ] Chapter 6
- [ ] Chapter 7
- [ ] Chapter 8
- [ ] Chapter 9
- [ ] Chapter 10
- [ ] Chapter 11
- [ ] Chapter 12
- [ ] Chapter 13
- [ ] Chapter 14
- [ ] Chapter 15
- [ ] Chapter 16
- [ ] Chapter 17
- [ ] Chapter 18
- [ ] Chapter 19
- [ ] Chapter 20
- [ ] Chapter 21
</details>

**Following chapters have had their content reviewed and reconsidered:**
<details>
   <summary> <i>Click to Expand</i> </summary>

- [ ] Chapter 1
- [ ] Chapter 2
- [ ] Chapter 3
- [ ] Chapter 4
- [ ] Chapter 5
- [ ] Chapter 6
- [ ] Chapter 7
- [ ] Chapter 8
- [ ] Chapter 9
- [ ] Chapter 10
- [ ] Chapter 11
- [ ] Chapter 12
- [ ] Chapter 13
- [ ] Chapter 14
- [ ] Chapter 15
- [ ] Chapter 16
- [ ] Chapter 17
- [ ] Chapter 18
- [ ] Chapter 19
- [ ] Chapter 20
- [ ] Chapter 21
</details>

**Comment by hdolinh** [comment]
In quarto book yml add:
```
  html:
    link-external-newwindow: true
```

This will make all links in book open in new window

**Comment by dvirlar2** [comment]
Chapter 1 Edits:

**Comment by dvirlar2** [comment]
Chapter 2 Updates:

**Comment by dvirlar2** [comment]
Chapter 3 Updates:

**Comment by dvirlar2** [comment]
Chapter 4 Updates:

**Comment by dvirlar2** [comment]
Chapter 5 Updates:

**Comment by dvirlar2** [comment]
Chapter 6 Updates:

**Comment by dvirlar2** [comment]
Chapter 7 Updates:

**Comment by dvirlar2** [comment]
Chapter 8 Updates:

**Comment by dvirlar2** [comment]
Chapter 10 Updates:

**Comment by dvirlar2** [comment]
Chapter 11 Updates:

**Comment by dvirlar2** [comment]
Chapter 12 Updates:

**Comment by dvirlar2** [comment]
Chapter 13 Updates:

**Comment by dvirlar2** [comment]
Chapter 14 Updates:

**Comment by dvirlar2** [comment]
Chapter 15 Updates:

**Comment by dvirlar2** [comment]
Chapter 16 Updates:

**Comment by dvirlar2** [comment]
Chapter 17 Updates:

**Comment by dvirlar2** [comment]
Chapter 18 Updates:

**Comment by dvirlar2** [comment]
Chapter 19 Updates:

**Comment by dvirlar2** [comment]
Chapter 20 Updates:

**Comment by dvirlar2** [comment]
Chapter 21 Updates:

**Comment by dvirlar2** [comment]
Chapter 22 Updates:
