### ISSUE TITLE
Reproducibles -- `Custom_theme()` Update

### ISSUE THREAD

**Issue by dvirlar2** [NCEAS/nceas-training#175]
In Session 10, Functions and Packages, we create a custom ggplot theme using the following:

```
custom_theme <- function(base_size = 9) {
    ggplot2::theme(
      axis.ticks       = ggplot2::element_blank(),
      text             = ggplot2::element_text(family = 'Helvetica', color = 'gray30', size = base_size),
      plot.title       = ggplot2::element_text(size = ggplot2::rel(1.25), hjust = 0.5, face = 'bold'),
      panel.background = ggplot2::element_blank(),
      legend.position  = 'right',
      panel.border     = ggplot2::element_blank(),
      panel.grid.minor = ggplot2::element_blank(),
      panel.grid.major = ggplot2::element_line(colour = 'grey90', size = .25),
      legend.key       = ggplot2::element_rect(colour = NA, fill = NA),
      axis.line        = ggplot2::element_blank()
      )
}
```

When used to plot, a warning pops up that `element_line()` has been deprecated, and `line_width()` (or something similar, I forgot already) should be used instead. We should fix this in the training materials

**Comment by camilavargasp** [comment]
The `.qmd` version of this lesson has been updated to use `line_width()`.

See code [here](https://github.com/NCEAS/nceas-training/blob/f5661e2d7f072304368e5c300a58c0b9a77004e8/materials/sections/r-creating-functions.qmd#L222)
