### ISSUE TITLE
update git setup to include merge strategy

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/nceas-training#484]
It is very clunky to go back into the terminal and run `git config pull.rebase false` during the git lesson. It would be better to do this in get setup, as a global option, with the caveat that we explain at some point that this is what we are doing for the course, but you can also set it on a repo specific basis and that this is what you likely want to do using git moving forward. A brief (brief!) description of the fact that different merge strategies exist, and this is one of them, with a reference to more information would also be good.

The line to add is: `git config --global pull.rebase false`

**Comment by jeanetteclark** [comment]
We could also switch to using `usethis::use_git_config(pull.rebase = "false")` (and also use it for the other git setup stuff) and save ourselves a bunch of time

**Comment by camilavargasp** [comment]
I updated the `git-setup.qmd`  (see [commit](https://github.com/NCEAS/nceas-training/commit/a776276c592ddc88d0a0859f4924123b33a1eff5))

It now walks through:

- How to do the git and GitHub configurations using the `usethis` package. Note: there is a tab with console commands too.
- Added `usethis::use_git_config(pull.rebase = "false")` to the global configurations to avoid issues when collaborating with github
- Added a section explaining that you can modify your strategy for integrating changes at a repository level.
