### ISSUE TITLE
include `pins` package for downloads

### ISSUE THREAD

**Issue by jeanetteclark** [NCEAS/nceas-training#5]
https://pins.rstudio.com/

**Comment by mbjones** [comment]
I am incoporating `pins` in the lesson on portable data access, which ends with `contentid`. Partially added to the `2021-11-delta` branch. More fine tuning to come.

**Comment by mbjones** [comment]
`pins` is now briefly described in https://github.com/NCEAS/nceas-training/blob/2021-11-delta/materials/sections/data-identifers-contentid.Rmd.
