### ISSUE TITLE
Fix inconsistency in the two git modules around README.md and index.Rmd

### ISSUE THREAD

**Issue by amoeba** [NCEAS/nceas-training#86]
These got out of sync at some point. For Session 5 we need to be working with a README.md file but Session 5 talks about both a readme and an index.Rmd file.

**Comment by jeanetteclark** [comment]
I think I fixed all of these, though it might be worth it to go through and make the text of each file more consistent

**Comment by amoeba** [comment]
Thanks @jeanetteclark
