### ISSUE TITLE
Session 7: Data Modeling Fixes

### ISSUE THREAD

**Issue by laijasmine** [NCEAS/nceas-training#88]
- [x] 7.1.4 - spelling wold -` Note that, should one encounter a new species in the survey, we wold have to add new columns to the table. This is difficult to analyze, understand, and maintain.`
- [x] 7.1.6 Challenge - spelling diatram -`Draw a new ER diatram showing this re-designed data structure`
- [x] 7.1.6 Challenge - still references excalidraw, should be invision? - `Using the Excalidraw live session your instructor start`
- [x] 7.1.6 Challenge Maybe mention that the first identifier column is created automatically by the table and not part of the original data?

**Comment by amoeba** [comment]
Thanks for catching these @laijasmine!
